---
# this format works with oc-mirror 4.11 or higher
# Schema for this file is here https://github.com/openshift/oc-mirror/blob/release-4.11/pkg/api/v1alpha1/config_types.go#L13
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    # catalog example registry.redhat.io/redhat/redhat-operator-index:v4.10
    - catalog: <catalogindex>
      #full: true
      packages:
        # package name example odf-operator
        - name: <opname>
          channels:
            # channels name example stable-4.10
            - name: '<channel>'
              #operator version example 4.10.5
              minVersion: '<opversion>'
              maxVersion: '<opversion>'
