---
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
# Don't use storageConfig. Intent is to not cache locally. But upload the image directly to registry
archiveSize: 4
mirror:
  platform:
    channels:
    - name: stable-<ocpchannel>
      minVersion: <ocpversion>
      maxVersion: <ocpversion>
      shortestPath: true
    graph: true # Include Cincinnati upgrade graph image in imageset

---
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
# Don't use storageConfig. Intent is to not cache locally. But upload the image directly to registry
archiveSize: 4
mirror:
  #platform: platform field was used in nightly build.
  ocp:
    channels:
    - name: stable-<ocpchannel>
      versions:
      - '<ocpversion>'
      - '<ocpversion>'
    graph: true # Include Cincinnati upgrade graph image in imageset