---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
mirror:
  platform:
    channels:
    - name: stable-<ocpchannel>
      minVersion: <ocpversion>
      maxVersion: <ocpversion>
      shortestPath: true
    graph: true
